#!/bin/bash
java simulateur/Simulateur -mess 0101010101 -s
java simulateur/Simulateur -mess 2 -s
java simulateur/Simulateur -s
java simulateur/Simulateur -seed 98 -s -mess 4
java simulateur/Simulateur -seed 98 -s -mess 4
