#!/bin/bash
./simulateur -mess 10 -s -ti 300 0.5 
./simulateur -mess 100 -s -ti 5 1 10 0.5
./simulateur -mess 10 -s -srnpb 10 -form RZ -ti 300 0.5               
./simulateur -mess 100 -s -snrpb 5 -form NRZT -ti 5 1 10 0.5
